"""add verify token fields to users

Revision ID: 67ca3d24f4aa
Revises: 
Create Date: 2026-07-03 11:31:14.393527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ca3d24f4aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verify_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verify_token_expires')
        batch_op.drop_column('verify_token')

    # ### end Alembic commands ###
